// Generated by gencpp from file common/ScanMapStatus.msg
// DO NOT EDIT!


#ifndef COMMON_MESSAGE_SCANMAPSTATUS_H
#define COMMON_MESSAGE_SCANMAPSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace common
{
template <class ContainerAllocator>
struct ScanMapStatus_
{
  typedef ScanMapStatus_<ContainerAllocator> Type;

  ScanMapStatus_()
    : header()
    , scan_status()
    , file_name()  {
    }
  ScanMapStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , scan_status(_alloc)
    , file_name(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _scan_status_type;
  _scan_status_type scan_status;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _file_name_type;
  _file_name_type file_name;





  typedef boost::shared_ptr< ::common::ScanMapStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::common::ScanMapStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ScanMapStatus_

typedef ::common::ScanMapStatus_<std::allocator<void> > ScanMapStatus;

typedef boost::shared_ptr< ::common::ScanMapStatus > ScanMapStatusPtr;
typedef boost::shared_ptr< ::common::ScanMapStatus const> ScanMapStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::common::ScanMapStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::common::ScanMapStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::common::ScanMapStatus_<ContainerAllocator1> & lhs, const ::common::ScanMapStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.scan_status == rhs.scan_status &&
    lhs.file_name == rhs.file_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::common::ScanMapStatus_<ContainerAllocator1> & lhs, const ::common::ScanMapStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace common

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::common::ScanMapStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::common::ScanMapStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::ScanMapStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::common::ScanMapStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::ScanMapStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::common::ScanMapStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::common::ScanMapStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99a910d59af2cd6d4413707fa4ffd257";
  }

  static const char* value(const ::common::ScanMapStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99a910d59af2cd6dULL;
  static const uint64_t static_value2 = 0x4413707fa4ffd257ULL;
};

template<class ContainerAllocator>
struct DataType< ::common::ScanMapStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "common/ScanMapStatus";
  }

  static const char* value(const ::common::ScanMapStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::common::ScanMapStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ScanMapStatus.msg\n"
"\n"
"# Standard ROS message header\n"
"#   stamp: time of status update\n"
"#   frame_id: optional, can be empty\n"
"std_msgs/Header header\n"
"\n"
"# Scan status\n"
"# Valid values: idle, scanning, completed, failed\n"
"string scan_status\n"
"\n"
"# File name generated after scan is completed (if any)\n"
"string file_name\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::common::ScanMapStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::common::ScanMapStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.scan_status);
      stream.next(m.file_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ScanMapStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::common::ScanMapStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::common::ScanMapStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "scan_status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.scan_status);
    s << indent << "file_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.file_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMON_MESSAGE_SCANMAPSTATUS_H
